"""
Merges session log (pilot_PXX_results.csv, generated by run_2afc_pilot_v2.py)
with subject responses entered independently in CSV (columns: trial, response),
joining ON TRIAL NUMBER.

Example usage:
    python src/pilot/merge_responses.py pilot_P_pilot_01_results.csv participant_1.csv
"""

import sys
import pandas as pd
from scipy.stats import binomtest


def main():
    if len(sys.argv) != 3:
        print("Usage: python src/pilot/merge_responses.py <session_log.csv> <subject_responses.csv>")
        sys.exit(1)

    session_log_path, responses_path = sys.argv[1], sys.argv[2]

    session_log = pd.read_csv(session_log_path)
    responses = pd.read_csv(responses_path)

    if len(session_log) != len(responses):
        print(f"WARNING: number of trials in log ({len(session_log)}) != number "
              f"of responses ({len(responses)}). Check if the subject skipped "
              f"or duplicated a row.")

    merged = session_log.merge(responses, on="trial", how="left")
    merged["response"] = merged["response"].astype(str).str.strip()
    merged["correct_response"] = merged["correct_response"].astype(str).str.strip()
    merged["correct"] = (merged["response"] == merged["correct_response"]).astype(int)

    out_path = session_log_path.replace(".csv", "_merged.csv")
    merged.to_csv(out_path, index=False)

    n = len(merged)
    n_correct = merged["correct"].sum()
    pct = 100 * n_correct / n
    test = binomtest(int(n_correct), n, 0.5, alternative="greater")

    print(merged[["trial", "distance_1", "distance_2", "correct_response",
                  "response", "correct"]].to_string(index=False))
    print(f"\nResult: {n_correct}/{n} correct ({pct:.1f}%)")
    print(f"Binomial test vs. 50% chance: p = {test.pvalue:.4g}")
    print(f"Merged data saved to: {out_path}")


if __name__ == "__main__":
    main()