"""
Merges session log (pilot_PXX_results.csv, generated by run_2afc_pilot_v2.py)
with subject responses entered independently in CSV (columns: trial, response),
joining ON TRIAL NUMBER.

Example usage:
    python src/pilot/merge_responses.py pilot_P_pilot_01_results.csv participant_1.csv
"""

import sys
import pandas as pd
from scipy.stats import binomtest


def main():
    if len(sys.argv) != 3:

        sys.exit(1)

    session_log_path, responses_path = sys.argv[1], sys.argv[2]

    session_log = pd.read_csv(session_log_path)
    responses = pd.read_csv(responses_path)

    if len(session_log) != len(responses):


        pass
    merged = session_log.merge(responses, on="trial", how="left")
    merged["response"] = merged["response"].astype(str).str.strip()
    merged["correct_response"] = merged["correct_response"].astype(str).str.strip()
    merged["correct"] = (merged["response"] == merged["correct_response"]).astype(int)

    out_path = session_log_path.replace(".csv", "_merged.csv")
    merged.to_csv(out_path, index=False)

    n = len(merged)
    n_correct = merged["correct"].sum()
    pct = 100 * n_correct / n
    test = binomtest(int(n_correct), n, 0.5, alternative="greater")


if __name__ == "__main__":
    main()